# Custom Language File for Launcher Customizer

[ejs.app]
title = "Vixlet Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/jojo382/VixletLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/SZ4t4HNn6j"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "ยินดีต้อนรับเข้าสู่ Vixlet Launcher"
welcomeDescription = "ไม่ว่าคุณจะเพิ่งเริ่มต้นหรือกำลังหาโปรเจ็ค คุณก็สามารถมาที่นี่ได้เลย"
welcomeDescCTA = "กด ปุ่มด้านล่างเพื่อไปต่อเลย"
